name: chicagocrashes

on: workflow_dispatch

jobs:
  chicagocrashes-post:
    runs-on: macOS-latest
    env:
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - run: |
         brew install pkg-config
         brew install gdal proj geos
         export LDFLAGS="-L/usr/local/opt/libpq/lib"
         export CPPFLAGS="-I/usr/local/opt/libpq/include"
      - name: Create and post tweet
        run: Rscript core.R
